# Generated by Django 2.0.2 on 2018-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.IntegerField(max_length=50),
        ),
    ]
