# Generated by Django 2.0.2 on 2018-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180205_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
